### ISSUE TITLE
make yourself a billionaire 

### ISSUE THREAD

**Issue by lrgeoemtry** [Airbitz/edge-react-gui#610]
need to lock down the etherscan api to scan the contract addr fir params yo make it so you cant ne a billionaire. 
I stumbled upon this by thinking some tokens were 18 decimals, I then made the mess decimals than they were which "awarded me with billions" fun trick, bad bug

**Comment by paullinator** [comment]
Contract params are not queried from etherscan but need to be entered manually. Due to the number of duplicate ERC20 token names, it's hard to definitively determine which one is the right token. We also want this to be fully flexible for users to add any tokens regardless of what etherscan supports. Etherscan is ONLY used for querying balances and transactions once the user already knows the token parameters. This issue won't really be fixed. However for your own implementation of the code, you can hard code token parameters for your own token so the user doesn't have to "get it right".
